version: '3.9'

services:
    db:
        image: postgres:15
        container_name: dw-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tb
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        container_name: "tb-redis"
        image: redis:latest
        ports:
            - 6379:6379

